### ISSUE TITLE
"Dependent Upon" notification

### ISSUE THREAD

**Issue by ianlaidlaw** [atrauzzi/gerty#35]
Certain processes/services are dependent on others running. Sometimes it's hard to remember, or dig through the output to see why a process fails to start. Would be nice to have an indicator if you try to start a process and one of its dependents is not already running

**Comment by atrauzzi** [comment]
Great idea.  I think it merits some additional abstraction, which I think is dependent on some other stuff I have planned.  I'll take this as a requirement as part of that work.  Will keep this ticket open until then! :)

**Comment by atrauzzi** [comment]
Closing for now, but not forgotten. This concept is fairly advanced and might do well to be investigated later.

One alternative: A flag for services that marks them to start upon load, or to be start-able from a single button.  This was actually one of the earliest ideas I had when making Gerty.  I will absolutely dig this up when the time comes.
